### ISSUE TITLE
User specified chrome path

### ISSUE THREAD

**Issue by galaxyeye** [platonai/pulsarr#9]
Pulsar have to know the chrome home to play with it, a user specified path is required.

By default, pulsar searches the following paths for google chrome:

val CHROME_BINARY_SEARCH_PATHS = arrayOf(
    "/usr/bin/google-chrome-stable",
    "/usr/bin/google-chrome",
    "/opt/google/chrome/chrome",
    "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser"
)

**Comment by platonai** [comment]
There is already a system property "browser.chrome.path" to specify the chrome path:

val path = System.getProperty(CapabilityTypes.BROWSER_CHROME_PATH);

**Comment by galaxyeye** [comment]
On Windows 7:

C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

**Comment by platonai** [comment]
Pulsar-1.10.x supports external config file where the chrome path can be put in.
